name: hello_world
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

resolution: workspace

environment:
  sdk: ^3.11.0-169.0.dev

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
#  flutter_test:
#    sdk: flutter
  flutter_lints: ^6.0.0

